#!/system/bin/sh

bb=/data/local/tmp/busybox_file



$bb cp $bb /system/xbin/busybox
chown 0.2000 /system/xbin/busybox
chmod 755 /system/xbin/busybox
$bb ln -sf /system/xbin/busybox /system/xbin/[
$bb ln -sf /system/xbin/busybox /system/xbin/[[
$bb ln -sf /system/xbin/busybox /system/xbin/acpid
$bb ln -sf /system/xbin/busybox /system/xbin/add-shell
$bb ln -sf /system/xbin/busybox /system/xbin/addgroup
$bb ln -sf /system/xbin/busybox /system/xbin/adduser
$bb ln -sf /system/xbin/busybox /system/xbin/adjtimex
$bb ln -sf /system/xbin/busybox /system/xbin/arp
$bb ln -sf /system/xbin/busybox /system/xbin/arping
$bb ln -sf /system/xbin/busybox /system/xbin/ash
$bb ln -sf /system/xbin/busybox /system/xbin/awk
$bb ln -sf /system/xbin/busybox /system/xbin/base64
$bb ln -sf /system/xbin/busybox /system/xbin/basename
$bb ln -sf /system/xbin/busybox /system/xbin/beep
$bb ln -sf /system/xbin/busybox /system/xbin/blkid
$bb ln -sf /system/xbin/busybox /system/xbin/blockdev
$bb ln -sf /system/xbin/busybox /system/xbin/bootchartd
$bb ln -sf /system/xbin/busybox /system/xbin/brctl
$bb ln -sf /system/xbin/busybox /system/xbin/bunzip2
$bb ln -sf /system/xbin/busybox /system/xbin/bzcat
$bb ln -sf /system/xbin/busybox /system/xbin/bzip2
$bb ln -sf /system/xbin/busybox /system/xbin/cal
$bb ln -sf /system/xbin/busybox /system/xbin/cat
$bb ln -sf /system/xbin/busybox /system/xbin/catv
$bb ln -sf /system/xbin/busybox /system/xbin/chat
$bb ln -sf /system/xbin/busybox /system/xbin/chattr
$bb ln -sf /system/xbin/busybox /system/xbin/chgrp
$bb ln -sf /system/xbin/busybox /system/xbin/chmod
$bb ln -sf /system/xbin/busybox /system/xbin/chown
$bb ln -sf /system/xbin/busybox /system/xbin/chpasswd
$bb ln -sf /system/xbin/busybox /system/xbin/chpst
$bb ln -sf /system/xbin/busybox /system/xbin/chroot
$bb ln -sf /system/xbin/busybox /system/xbin/chrt
$bb ln -sf /system/xbin/busybox /system/xbin/chvt
$bb ln -sf /system/xbin/busybox /system/xbin/cksum
$bb ln -sf /system/xbin/busybox /system/xbin/clear
$bb ln -sf /system/xbin/busybox /system/xbin/cmp
$bb ln -sf /system/xbin/busybox /system/xbin/comm
$bb ln -sf /system/xbin/busybox /system/xbin/cp
$bb ln -sf /system/xbin/busybox /system/xbin/cpio
$bb ln -sf /system/xbin/busybox /system/xbin/crond
$bb ln -sf /system/xbin/busybox /system/xbin/crontab
$bb ln -sf /system/xbin/busybox /system/xbin/cryptpw
$bb ln -sf /system/xbin/busybox /system/xbin/cttyhack
$bb ln -sf /system/xbin/busybox /system/xbin/cut
$bb ln -sf /system/xbin/busybox /system/xbin/date
$bb ln -sf /system/xbin/busybox /system/xbin/dc
$bb ln -sf /system/xbin/busybox /system/xbin/dd
$bb ln -sf /system/xbin/busybox /system/xbin/deallocvt
$bb ln -sf /system/xbin/busybox /system/xbin/delgroup
$bb ln -sf /system/xbin/busybox /system/xbin/deluser
$bb ln -sf /system/xbin/busybox /system/xbin/depmod
$bb ln -sf /system/xbin/busybox /system/xbin/devmem
$bb ln -sf /system/xbin/busybox /system/xbin/df
$bb ln -sf /system/xbin/busybox /system/xbin/dhcprelay
$bb ln -sf /system/xbin/busybox /system/xbin/diff
$bb ln -sf /system/xbin/busybox /system/xbin/dirname
$bb ln -sf /system/xbin/busybox /system/xbin/dmesg
$bb ln -sf /system/xbin/busybox /system/xbin/dnsd
$bb ln -sf /system/xbin/busybox /system/xbin/dnsdomainname
$bb ln -sf /system/xbin/busybox /system/xbin/dos2unix
$bb ln -sf /system/xbin/busybox /system/xbin/du
$bb ln -sf /system/xbin/busybox /system/xbin/dumpkmap
$bb ln -sf /system/xbin/busybox /system/xbin/dumpleases
$bb ln -sf /system/xbin/busybox /system/xbin/echo
$bb ln -sf /system/xbin/busybox /system/xbin/ed
$bb ln -sf /system/xbin/busybox /system/xbin/egrep
$bb ln -sf /system/xbin/busybox /system/xbin/eject
$bb ln -sf /system/xbin/busybox /system/xbin/env
$bb ln -sf /system/xbin/busybox /system/xbin/envdir
$bb ln -sf /system/xbin/busybox /system/xbin/envuidgid
$bb ln -sf /system/xbin/busybox /system/xbin/ether-wake
$bb ln -sf /system/xbin/busybox /system/xbin/expand
$bb ln -sf /system/xbin/busybox /system/xbin/expr
$bb ln -sf /system/xbin/busybox /system/xbin/fakeidentd
$bb ln -sf /system/xbin/busybox /system/xbin/false
$bb ln -sf /system/xbin/busybox /system/xbin/fbset
$bb ln -sf /system/xbin/busybox /system/xbin/fbsplash
$bb ln -sf /system/xbin/busybox /system/xbin/fdflush
$bb ln -sf /system/xbin/busybox /system/xbin/fdformat
$bb ln -sf /system/xbin/busybox /system/xbin/fdisk
$bb ln -sf /system/xbin/busybox /system/xbin/fgconsole
$bb ln -sf /system/xbin/busybox /system/xbin/fgrep
$bb ln -sf /system/xbin/busybox /system/xbin/find
$bb ln -sf /system/xbin/busybox /system/xbin/findfs
$bb ln -sf /system/xbin/busybox /system/xbin/flock
$bb ln -sf /system/xbin/busybox /system/xbin/fold
$bb ln -sf /system/xbin/busybox /system/xbin/free
$bb ln -sf /system/xbin/busybox /system/xbin/freeramdisk
$bb ln -sf /system/xbin/busybox /system/xbin/fsck
$bb ln -sf /system/xbin/busybox /system/xbin/fsck.minix
$bb ln -sf /system/xbin/busybox /system/xbin/fsync
$bb ln -sf /system/xbin/busybox /system/xbin/ftpd
$bb ln -sf /system/xbin/busybox /system/xbin/ftpget
$bb ln -sf /system/xbin/busybox /system/xbin/ftpput
$bb ln -sf /system/xbin/busybox /system/xbin/fuser
$bb ln -sf /system/xbin/busybox /system/xbin/getopt
$bb ln -sf /system/xbin/busybox /system/xbin/getty
$bb ln -sf /system/xbin/busybox /system/xbin/grep
$bb ln -sf /system/xbin/busybox /system/xbin/groups
$bb ln -sf /system/xbin/busybox /system/xbin/gunzip
$bb ln -sf /system/xbin/busybox /system/xbin/gzip
$bb ln -sf /system/xbin/busybox /system/xbin/halt
$bb ln -sf /system/xbin/busybox /system/xbin/hd
$bb ln -sf /system/xbin/busybox /system/xbin/hdparm
$bb ln -sf /system/xbin/busybox /system/xbin/head
$bb ln -sf /system/xbin/busybox /system/xbin/hexdump
$bb ln -sf /system/xbin/busybox /system/xbin/hostid
$bb ln -sf /system/xbin/busybox /system/xbin/hostname
$bb ln -sf /system/xbin/busybox /system/xbin/httpd
$bb ln -sf /system/xbin/busybox /system/xbin/hush
$bb ln -sf /system/xbin/busybox /system/xbin/hwclock
$bb ln -sf /system/xbin/busybox /system/xbin/id
$bb ln -sf /system/xbin/busybox /system/xbin/ifconfig
$bb ln -sf /system/xbin/busybox /system/xbin/ifdown
$bb ln -sf /system/xbin/busybox /system/xbin/ifenslave
$bb ln -sf /system/xbin/busybox /system/xbin/ifplugd
$bb ln -sf /system/xbin/busybox /system/xbin/ifup
$bb ln -sf /system/xbin/busybox /system/xbin/inetd
$bb ln -sf /system/xbin/busybox /system/xbin/init
$bb ln -sf /system/xbin/busybox /system/xbin/insmod
$bb ln -sf /system/xbin/busybox /system/xbin/install
$bb ln -sf /system/xbin/busybox /system/xbin/ionice
$bb ln -sf /system/xbin/busybox /system/xbin/iostat
$bb ln -sf /system/xbin/busybox /system/xbin/ip
$bb ln -sf /system/xbin/busybox /system/xbin/ipaddr
$bb ln -sf /system/xbin/busybox /system/xbin/ipcalc
$bb ln -sf /system/xbin/busybox /system/xbin/ipcrm
$bb ln -sf /system/xbin/busybox /system/xbin/ipcs
$bb ln -sf /system/xbin/busybox /system/xbin/iplink
$bb ln -sf /system/xbin/busybox /system/xbin/iproute
$bb ln -sf /system/xbin/busybox /system/xbin/iprule
$bb ln -sf /system/xbin/busybox /system/xbin/iptunnel
$bb ln -sf /system/xbin/busybox /system/xbin/kbd_mode
$bb ln -sf /system/xbin/busybox /system/xbin/kill
$bb ln -sf /system/xbin/busybox /system/xbin/killall
$bb ln -sf /system/xbin/busybox /system/xbin/killall5
$bb ln -sf /system/xbin/busybox /system/xbin/klogd
$bb ln -sf /system/xbin/busybox /system/xbin/last
$bb ln -sf /system/xbin/busybox /system/xbin/less
$bb ln -sf /system/xbin/busybox /system/xbin/linux32
$bb ln -sf /system/xbin/busybox /system/xbin/linux64
$bb ln -sf /system/xbin/busybox /system/xbin/linuxrc
$bb ln -sf /system/xbin/busybox /system/xbin/ln
$bb ln -sf /system/xbin/busybox /system/xbin/loadfont
$bb ln -sf /system/xbin/busybox /system/xbin/loadkmap
$bb ln -sf /system/xbin/busybox /system/xbin/logger
$bb ln -sf /system/xbin/busybox /system/xbin/login
$bb ln -sf /system/xbin/busybox /system/xbin/logname
$bb ln -sf /system/xbin/busybox /system/xbin/logread
$bb ln -sf /system/xbin/busybox /system/xbin/losetup
$bb ln -sf /system/xbin/busybox /system/xbin/lpd
$bb ln -sf /system/xbin/busybox /system/xbin/lpq
$bb ln -sf /system/xbin/busybox /system/xbin/lpr
$bb ln -sf /system/xbin/busybox /system/xbin/ls
$bb ln -sf /system/xbin/busybox /system/xbin/lsattr
$bb ln -sf /system/xbin/busybox /system/xbin/lsmod
$bb ln -sf /system/xbin/busybox /system/xbin/lspci
$bb ln -sf /system/xbin/busybox /system/xbin/lsusb
$bb ln -sf /system/xbin/busybox /system/xbin/lzcat
$bb ln -sf /system/xbin/busybox /system/xbin/lzma
$bb ln -sf /system/xbin/busybox /system/xbin/lzop
$bb ln -sf /system/xbin/busybox /system/xbin/lzopcat
$bb ln -sf /system/xbin/busybox /system/xbin/makedevs
$bb ln -sf /system/xbin/busybox /system/xbin/makemime
$bb ln -sf /system/xbin/busybox /system/xbin/man
$bb ln -sf /system/xbin/busybox /system/xbin/md5sum
$bb ln -sf /system/xbin/busybox /system/xbin/mdev
$bb ln -sf /system/xbin/busybox /system/xbin/mesg
$bb ln -sf /system/xbin/busybox /system/xbin/microcom
$bb ln -sf /system/xbin/busybox /system/xbin/mkdir
$bb ln -sf /system/xbin/busybox /system/xbin/mkdosfs
$bb ln -sf /system/xbin/busybox /system/xbin/mke2fs
$bb ln -sf /system/xbin/busybox /system/xbin/mkfifo
$bb ln -sf /system/xbin/busybox /system/xbin/mkfs.ext2
$bb ln -sf /system/xbin/busybox /system/xbin/mkfs.minix
$bb ln -sf /system/xbin/busybox /system/xbin/mkfs.vfat
$bb ln -sf /system/xbin/busybox /system/xbin/mknod
$bb ln -sf /system/xbin/busybox /system/xbin/mkpasswd
$bb ln -sf /system/xbin/busybox /system/xbin/mkswap
$bb ln -sf /system/xbin/busybox /system/xbin/mktemp
$bb ln -sf /system/xbin/busybox /system/xbin/modinfo
$bb ln -sf /system/xbin/busybox /system/xbin/modprobe
$bb ln -sf /system/xbin/busybox /system/xbin/more
$bb ln -sf /system/xbin/busybox /system/xbin/mount
$bb ln -sf /system/xbin/busybox /system/xbin/mountpoint
$bb ln -sf /system/xbin/busybox /system/xbin/mpstat
$bb ln -sf /system/xbin/busybox /system/xbin/mt
$bb ln -sf /system/xbin/busybox /system/xbin/mv
$bb ln -sf /system/xbin/busybox /system/xbin/nameif
$bb ln -sf /system/xbin/busybox /system/xbin/nbd-client
$bb ln -sf /system/xbin/busybox /system/xbin/nc
$bb ln -sf /system/xbin/busybox /system/xbin/netstat
$bb ln -sf /system/xbin/busybox /system/xbin/nice
$bb ln -sf /system/xbin/busybox /system/xbin/nmeter
$bb ln -sf /system/xbin/busybox /system/xbin/nohup
$bb ln -sf /system/xbin/busybox /system/xbin/nslookup
$bb ln -sf /system/xbin/busybox /system/xbin/ntpd
$bb ln -sf /system/xbin/busybox /system/xbin/od
$bb ln -sf /system/xbin/busybox /system/xbin/openvt
$bb ln -sf /system/xbin/busybox /system/xbin/passwd
$bb ln -sf /system/xbin/busybox /system/xbin/patch
$bb ln -sf /system/xbin/busybox /system/xbin/pgrep
$bb ln -sf /system/xbin/busybox /system/xbin/pidof
$bb ln -sf /system/xbin/busybox /system/xbin/ping
$bb ln -sf /system/xbin/busybox /system/xbin/ping6
$bb ln -sf /system/xbin/busybox /system/xbin/pipe_progress
$bb ln -sf /system/xbin/busybox /system/xbin/pivot_root
$bb ln -sf /system/xbin/busybox /system/xbin/pkill
$bb ln -sf /system/xbin/busybox /system/xbin/pmap
$bb ln -sf /system/xbin/busybox /system/xbin/popmaildir
$bb ln -sf /system/xbin/busybox /system/xbin/poweroff
$bb ln -sf /system/xbin/busybox /system/xbin/powertop
$bb ln -sf /system/xbin/busybox /system/xbin/printenv
$bb ln -sf /system/xbin/busybox /system/xbin/printf
$bb ln -sf /system/xbin/busybox /system/xbin/ps
$bb ln -sf /system/xbin/busybox /system/xbin/pscan
$bb ln -sf /system/xbin/busybox /system/xbin/pstree
$bb ln -sf /system/xbin/busybox /system/xbin/pwd
$bb ln -sf /system/xbin/busybox /system/xbin/pwdx
$bb ln -sf /system/xbin/busybox /system/xbin/raidautorun
$bb ln -sf /system/xbin/busybox /system/xbin/rdate
$bb ln -sf /system/xbin/busybox /system/xbin/rdev
$bb ln -sf /system/xbin/busybox /system/xbin/readahead
$bb ln -sf /system/xbin/busybox /system/xbin/readlink
$bb ln -sf /system/xbin/busybox /system/xbin/readprofile
$bb ln -sf /system/xbin/busybox /system/xbin/realpath
$bb ln -sf /system/xbin/busybox /system/xbin/reboot
$bb ln -sf /system/xbin/busybox /system/xbin/reformime
$bb ln -sf /system/xbin/busybox /system/xbin/remove-shell
$bb ln -sf /system/xbin/busybox /system/xbin/renice
$bb ln -sf /system/xbin/busybox /system/xbin/reset
$bb ln -sf /system/xbin/busybox /system/xbin/resize
$bb ln -sf /system/xbin/busybox /system/xbin/rev
$bb ln -sf /system/xbin/busybox /system/xbin/rm
$bb ln -sf /system/xbin/busybox /system/xbin/rmdir
$bb ln -sf /system/xbin/busybox /system/xbin/rmmod
$bb ln -sf /system/xbin/busybox /system/xbin/route
$bb ln -sf /system/xbin/busybox /system/xbin/rpm
$bb ln -sf /system/xbin/busybox /system/xbin/rpm2cpio
$bb ln -sf /system/xbin/busybox /system/xbin/rtcwake
$bb ln -sf /system/xbin/busybox /system/xbin/run-parts
$bb ln -sf /system/xbin/busybox /system/xbin/runlevel
$bb ln -sf /system/xbin/busybox /system/xbin/runsv
$bb ln -sf /system/xbin/busybox /system/xbin/runsvdir
$bb ln -sf /system/xbin/busybox /system/xbin/rx
$bb ln -sf /system/xbin/busybox /system/xbin/script
$bb ln -sf /system/xbin/busybox /system/xbin/scriptreplay
$bb ln -sf /system/xbin/busybox /system/xbin/sed
$bb ln -sf /system/xbin/busybox /system/xbin/sendmail
$bb ln -sf /system/xbin/busybox /system/xbin/seq
$bb ln -sf /system/xbin/busybox /system/xbin/setarch
$bb ln -sf /system/xbin/busybox /system/xbin/setconsole
$bb ln -sf /system/xbin/busybox /system/xbin/setfont
$bb ln -sf /system/xbin/busybox /system/xbin/setkeycodes
$bb ln -sf /system/xbin/busybox /system/xbin/setlogcons
$bb ln -sf /system/xbin/busybox /system/xbin/setserial
$bb ln -sf /system/xbin/busybox /system/xbin/setsid
$bb ln -sf /system/xbin/busybox /system/xbin/setuidgid
$bb ln -sf /system/xbin/busybox /system/xbin/sh
$bb ln -sf /system/xbin/busybox /system/xbin/sha1sum
$bb ln -sf /system/xbin/busybox /system/xbin/sha256sum
$bb ln -sf /system/xbin/busybox /system/xbin/sha512sum
$bb ln -sf /system/xbin/busybox /system/xbin/showkey
$bb ln -sf /system/xbin/busybox /system/xbin/slattach
$bb ln -sf /system/xbin/busybox /system/xbin/sleep
$bb ln -sf /system/xbin/busybox /system/xbin/smemcap
$bb ln -sf /system/xbin/busybox /system/xbin/softlimit
$bb ln -sf /system/xbin/busybox /system/xbin/sort
$bb ln -sf /system/xbin/busybox /system/xbin/split
$bb ln -sf /system/xbin/busybox /system/xbin/start-stop-daemon
$bb ln -sf /system/xbin/busybox /system/xbin/stat
$bb ln -sf /system/xbin/busybox /system/xbin/strings
$bb ln -sf /system/xbin/busybox /system/xbin/stty
$bb ln -sf /system/xbin/busybox /system/xbin/sulogin
$bb ln -sf /system/xbin/busybox /system/xbin/sum
$bb ln -sf /system/xbin/busybox /system/xbin/sv
$bb ln -sf /system/xbin/busybox /system/xbin/svlogd
$bb ln -sf /system/xbin/busybox /system/xbin/swapoff
$bb ln -sf /system/xbin/busybox /system/xbin/swapon
$bb ln -sf /system/xbin/busybox /system/xbin/switch_root
$bb ln -sf /system/xbin/busybox /system/xbin/sync
$bb ln -sf /system/xbin/busybox /system/xbin/sysctl
$bb ln -sf /system/xbin/busybox /system/xbin/syslogd
$bb ln -sf /system/xbin/busybox /system/xbin/tac
$bb ln -sf /system/xbin/busybox /system/xbin/tail
$bb ln -sf /system/xbin/busybox /system/xbin/tar
$bb ln -sf /system/xbin/busybox /system/xbin/tcpsvd
$bb ln -sf /system/xbin/busybox /system/xbin/tee
$bb ln -sf /system/xbin/busybox /system/xbin/telnet
$bb ln -sf /system/xbin/busybox /system/xbin/telnetd
$bb ln -sf /system/xbin/busybox /system/xbin/test
$bb ln -sf /system/xbin/busybox /system/xbin/tftp
$bb ln -sf /system/xbin/busybox /system/xbin/tftpd
$bb ln -sf /system/xbin/busybox /system/xbin/time
$bb ln -sf /system/xbin/busybox /system/xbin/timeout
$bb ln -sf /system/xbin/busybox /system/xbin/top
$bb ln -sf /system/xbin/busybox /system/xbin/touch
$bb ln -sf /system/xbin/busybox /system/xbin/tr
$bb ln -sf /system/xbin/busybox /system/xbin/traceroute
$bb ln -sf /system/xbin/busybox /system/xbin/traceroute6
$bb ln -sf /system/xbin/busybox /system/xbin/true
$bb ln -sf /system/xbin/busybox /system/xbin/tty
$bb ln -sf /system/xbin/busybox /system/xbin/ttysize
$bb ln -sf /system/xbin/busybox /system/xbin/tunctl
$bb ln -sf /system/xbin/busybox /system/xbin/ubiattach
$bb ln -sf /system/xbin/busybox /system/xbin/ubidetach
$bb ln -sf /system/xbin/busybox /system/xbin/ubimkvol
$bb ln -sf /system/xbin/busybox /system/xbin/ubirmvol
$bb ln -sf /system/xbin/busybox /system/xbin/ubirsvol
$bb ln -sf /system/xbin/busybox /system/xbin/ubiupdatevol
$bb ln -sf /system/xbin/busybox /system/xbin/udhcpc
$bb ln -sf /system/xbin/busybox /system/xbin/udhcpd
$bb ln -sf /system/xbin/busybox /system/xbin/udpsvd
$bb ln -sf /system/xbin/busybox /system/xbin/umount
$bb ln -sf /system/xbin/busybox /system/xbin/uname
$bb ln -sf /system/xbin/busybox /system/xbin/unexpand
$bb ln -sf /system/xbin/busybox /system/xbin/uniq
$bb ln -sf /system/xbin/busybox /system/xbin/unix2dos
$bb ln -sf /system/xbin/busybox /system/xbin/unlzma
$bb ln -sf /system/xbin/busybox /system/xbin/unlzop
$bb ln -sf /system/xbin/busybox /system/xbin/unxz
$bb ln -sf /system/xbin/busybox /system/xbin/unzip
$bb ln -sf /system/xbin/busybox /system/xbin/uptime
$bb ln -sf /system/xbin/busybox /system/xbin/users
$bb ln -sf /system/xbin/busybox /system/xbin/usleep
$bb ln -sf /system/xbin/busybox /system/xbin/uudecode
$bb ln -sf /system/xbin/busybox /system/xbin/uuencode
$bb ln -sf /system/xbin/busybox /system/xbin/vconfig
$bb ln -sf /system/xbin/busybox /system/xbin/vi
$bb ln -sf /system/xbin/busybox /system/xbin/vlock
$bb ln -sf /system/xbin/busybox /system/xbin/volname
$bb ln -sf /system/xbin/busybox /system/xbin/wall
$bb ln -sf /system/xbin/busybox /system/xbin/watch
$bb ln -sf /system/xbin/busybox /system/xbin/watchdog
$bb ln -sf /system/xbin/busybox /system/xbin/wc
$bb ln -sf /system/xbin/busybox /system/xbin/wget
$bb ln -sf /system/xbin/busybox /system/xbin/which
$bb ln -sf /system/xbin/busybox /system/xbin/who
$bb ln -sf /system/xbin/busybox /system/xbin/whoami
$bb ln -sf /system/xbin/busybox /system/xbin/whois
$bb ln -sf /system/xbin/busybox /system/xbin/xargs
$bb ln -sf /system/xbin/busybox /system/xbin/xz
$bb ln -sf /system/xbin/busybox /system/xbin/xzcat
$bb ln -sf /system/xbin/busybox /system/xbin/yes
$bb ln -sf /system/xbin/busybox /system/xbin/zcat
$bb ln -sf /system/xbin/busybox /system/xbin/zcip
